//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradeprogram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorrectStuHWDBEntities : DbContext
    {
        public CorrectStuHWDBEntities()
            : base("name=CorrectStuHWDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<CompileFail_Stu> CompileFail_Stu { get; set; }
        public virtual DbSet<Correct_Answer> Correct_Answer { get; set; }
        public virtual DbSet<HW_Exam> HW_Exam { get; set; }
        public virtual DbSet<HW_Exam_File> HW_Exam_File { get; set; }
        public virtual DbSet<InstructorPro> InstructorPro { get; set; }
        public virtual DbSet<ORCS_ProgramFileUploadData> ORCS_ProgramFileUploadData { get; set; }
        public virtual DbSet<QuestionIndex> QuestionIndex { get; set; }
        public virtual DbSet<StuCouHWDe_prog> StuCouHWDe_prog { get; set; }
        public virtual DbSet<StuPro> StuPro { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Take_Course> Take_Course { get; set; }
        public virtual DbSet<QuestionMode> QuestionMode { get; set; }
    }
}
