//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gradeprogram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Take_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Take_Course()
        {
            this.HW_Exam = new HashSet<HW_Exam>();
        }
    
        public string Student_ID { get; set; }
        public int Course_ID { get; set; }
        public string Stu_Personal_HW_Exam_ID { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HW_Exam> HW_Exam { get; set; }
        public virtual StuPro StuPro { get; set; }
    }
}
